### ISSUE TITLE
Warning: desiredCapacity has been configured. Be aware this will reset the size of your AutoScalingGroup on every deployment

### ISSUE THREAD

**Issue by moltar** [AndrewGuenther/cdk-fck-nat#286]
> [Warning at /.../FckNatAsg] desiredCapacity has been configured. Be aware this will reset the size of your AutoScalingGroup on every deployment. See https://github.com/aws/aws-cdk/issues/5215 [ack: @aws-cdk/aws-autoscaling:desiredCapacitySet]

If this is intended, perhaps we can ack this warning in the construct?

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.Annotations.html#acknowledgewbrwarningid-message

**Comment by AndrewGuenther** [comment]
@moltar I thought this would be a quick win, but turns out CDK doesn't really make this possible. As a construct publisher, I cannot blanked acknowledge warnings generated by my construct. That acknowledge warning API only works with an instance of a construct, not the class.

Unless there's some other annotation that can be applied to the class (there doesn't appear to be one) this is sadly not doable.

**Comment by AndrewGuenther** [comment]
After some coffee I just realized it is 100% in my power to do this. Re-opening.

**Comment by moltar** [comment]
Thank you 🙏😀
